"""update models

Revision ID: 6263346d2455
Revises: 84de1a031ff1
Create Date: 2026-01-17 02:17:36.537503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6263346d2455'
down_revision: Union[str, Sequence[str], None] = '84de1a031ff1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'memories', ['user_id', 'key', 'scope'])
    op.create_unique_constraint(None, 'skill_favorites', ['user_id', 'skill_id'])
    op.create_unique_constraint(None, 'skill_ratings', ['user_id', 'skill_id'])
    op.create_unique_constraint(None, 'skill_suggestions', ['session_id', 'skill_id'])
    op.add_column('skill_versions', sa.Column('parent_version_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_skill_versions_parent_version_id'), 'skill_versions', ['parent_version_id'], unique=False)
    op.create_unique_constraint(None, 'skill_versions', ['skill_id', 'version'])
    op.add_column('skills', sa.Column('deleted', sa.Boolean(), nullable=False))
    op.add_column('skills', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('role', sa.Enum('user', 'admin', name='user_role'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    op.drop_column('skills', 'deleted_at')
    op.drop_column('skills', 'deleted')
    op.drop_constraint(None, 'skill_versions', type_='unique')
    op.drop_index(op.f('ix_skill_versions_parent_version_id'), table_name='skill_versions')
    op.drop_column('skill_versions', 'parent_version_id')
    op.drop_constraint(None, 'skill_suggestions', type_='unique')
    op.drop_constraint(None, 'skill_ratings', type_='unique')
    op.drop_constraint(None, 'skill_favorites', type_='unique')
    op.drop_constraint(None, 'memories', type_='unique')
    # ### end Alembic commands ###
